[package]
name = "key_forge"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1"
lazy_static = "1.4"
rand = "0.8"
rustyline = "10.0"
clear_screen = "0.1.0"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
