[package]
name = "keyforge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
colored = "2.1"
lazy_static = "1.4"
rustyline = "12.0.0"
rustyline-derive = "0.1.0"
clear_screen = "0.1.0"